// Auto generated by env plugin. DO NOT EDIT.
type Env = {
  ONOTTD_WEATHER_MODE: string;
  ONOTTD_DEFAULT_LATITUDE: string;
  ONOTTD_DEFAULT_LONGITUDE: string;
  ONOTTD_DEFAULT_LOCATION_NAME: string;
  ONOTTD_OPEN_METEO_WEATHER_URL: string;
  ONOTTD_OPEN_METEO_AIR_QUALITY_URL: string;
};

interface ImportMeta {
  readonly env: Env & {};
}
