/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AvatarSetupRoute } from '../pages/avatar-setup';
import { Route as _IndexRoute } from '../pages/';
import { Route as _OnboardingRoute } from '../pages/onboarding';
import { Route as _SettingsRoute } from '../pages/settings';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/avatar-setup': (typeof _AvatarSetupRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/onboarding': (typeof _OnboardingRoute)['_inputType'];
    '/settings': (typeof _SettingsRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/avatar-setup': (typeof _AvatarSetupRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/onboarding': (typeof _OnboardingRoute)['_outputType'];
    '/settings': (typeof _SettingsRoute)['_outputType'];
  }
}
